# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PhoneValidator_pb2 as PhoneValidator__pb2


class NumbererStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateNumber = channel.unary_unary(
                '/Numberer/ValidateNumber',
                request_serializer=PhoneValidator__pb2.NumberRequest.SerializeToString,
                response_deserializer=PhoneValidator__pb2.ResultReply.FromString,
                )


class NumbererServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumbererServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateNumber,
                    request_deserializer=PhoneValidator__pb2.NumberRequest.FromString,
                    response_serializer=PhoneValidator__pb2.ResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Numberer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Numberer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Numberer/ValidateNumber',
            PhoneValidator__pb2.NumberRequest.SerializeToString,
            PhoneValidator__pb2.ResultReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
